from typing import Protocol


class PLogger(Protocol):
    def debug(self, msg: object) -> None: ...
    def info(self, msg: object) -> None: ...
    def warning(self, msg: object) -> None: ...
    def error(self, msg: object) -> None: ...
    def exception(self, msg: object) -> None: ...
    def critical(self, msg: object) -> None: ...

    def log(self, level: int, msg: object) -> None: ...
