# referenced from https://github.com/tox-dev/tox-gh
name: "Nox: Coverage"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
    paths:
      - ".github/workflows/nox-test.yml"
      - ".github/workflows/nox-cov.yml"
      - ".github/workflows/_nox-session.yml"
      - "src/**"
      - "tests/**"
      - "noxfile.py"
      - "pyproject.toml"
      - "uv.lock"
      - "requirements.txt"
      - "requirements-dev.txt"
      - "codecov.yml"
      - "MANIFEST.in"
  pull_request:
    paths:
      - ".github/workflows/nox-test.yml"
      - ".github/workflows/nox-cov.yml"
      - ".github/workflows/_nox-session.yml"
      - "src/**"
      - "tests/**"
      - "noxfile.py"
      - "pyproject.toml"
      - "uv.lock"
      - "requirements.txt"
      - "requirements-dev.txt"
      - "codecov.yml"
      - "MANIFEST.in"

concurrency:
  group: nox-cov-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  nox-cov:
    uses: ./.github/workflows/_nox-session.yml
    with:
      os: ubuntu-latest
      python-version: "3.13"
      session: cov
      upload-codecov: true
    secrets: inherit
