# referenced from https://github.com/tox-dev/tox-gh
name: "Nox: Test"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
    paths:
      - ".github/workflows/nox-test.yml"
      - ".github/workflows/nox-cov.yml"
      - ".github/workflows/_nox-session.yml"
      - "src/**"
      - "tests/**"
      - "noxfile.py"
      - "pyproject.toml"
      - "uv.lock"
      - "requirements.txt"
      - "requirements-dev.txt"
      - "MANIFEST.in"
  pull_request:
    paths:
      - ".github/workflows/nox-test.yml"
      - ".github/workflows/nox-cov.yml"
      - ".github/workflows/_nox-session.yml"
      - "src/**"
      - "tests/**"
      - "noxfile.py"
      - "pyproject.toml"
      - "uv.lock"
      - "requirements.txt"
      - "requirements-dev.txt"
      - "MANIFEST.in"

concurrency:
  group: nox-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  nox-test:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        env:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    uses: ./.github/workflows/_nox-session.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.env }}
      session: test
    secrets: inherit

  tests-pass:
    # used for auto-merge.yml
    name: tests-pass
    runs-on: ubuntu-latest
    needs: [nox-test]
    if: ${{ always() }}
    steps:
      - name: Fail if any matrix job failed
        run: |
          if [ "${{ needs.nox-test.result }}" != "success" ]; then
            echo "Matrix did not fully pass"
            exit 1
          fi
        shell: bash
